### ISSUE TITLE
Context.OperationsAsync кидает исключение "OpenApiInvalidResponseException: Unable to handle response" с пустым Response.

### ISSUE THREAD

**Issue by RWander** [TinkoffCreditSystems/invest-openapi-csharp-sdk#46]
Метод Context.OperationsAsync кидает исключение "OpenApiInvalidResponseException: Unable to handle response" (см ниже). При этом Response пустой.

```
 _---> Tinkoff.Trading.OpenApi.Network.OpenApiInvalidResponseException: Unable to handle response.
Response:

 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at async Task<OpenApiResponse<TOut>> Tinkoff.Trading.OpenApi.Network.Connection<TContext>.HandleResponseAsync<TOut>(HttpResponseMessage response)
   --- End of inner exception stack trace ---
   at async Task<OpenApiResponse<TOut>> Tinkoff.Trading.OpenApi.Network.Connection<TContext>.HandleResponseAsync<TOut>(HttpResponseMessage response)
   at async Task<OpenApiResponse<TPayload>> Tinkoff.Trading.OpenApi.Network.Connection<TContext>.SendGetRequestAsync<TPayload>(string path)
   at async Task<List<Operation>> Tinkoff.Trading.OpenApi.Network.Context.OperationsAsync(DateTime from, DateTime to, string figi, string brokerAccountId)_
```

**Comment by olsh** [comment]
Частично этот PR пофиксит
https://github.com/TinkoffCreditSystems/invest-openapi-csharp-sdk/pull/45

Когда слишком много запросов, возвращается пустой респонс.

**Comment by rus-art** [comment]
Проверьте, улучшилась ли обработка ошибок?

**Comment by EvgenyBatalin** [comment]
С последней версией из Nuget (1.5.0) - никаких изменений. Все так же падает с пустным Response.

**Comment by RWander** [comment]
> Проверьте, улучшилась ли обработка ошибок?

Стало лучше немного. Появилась информация о причине ошибки, но не для всех ошибкой. Ошибки с пустым Response по-прежнему проскакивают.

**Comment by RWander** [comment]
Вместо пустого Response сейчас возвращается неинформативный OpenApiException: INTERNAL_ERROR:


 ---> Tinkoff.Trading.OpenApi.Network.OpenApiException: INTERNAL_ERROR: INTERNAL_ERROR (a715629199c52eb5).
   at async Task<OpenApiResponse<TOut>> Tinkoff.Trading.OpenApi.Network.Connection<TContext>.HandleResponseAsync<TOut>(HttpResponseMessage response) in C:/!self/github/smart-income/Libs/forks/Tinkoff.Trading.OpenApi/src/Tinkoff.Trading.OpenApi/Network/Connection.cs:line 118
   at async Task<OpenApiResponse<TPayload>> Tinkoff.Trading.OpenApi.Network.Connection<TContext>.SendGetRequestAsync<TPayload>(string path) in C:/!self/github/smart-income/Libs/forks/Tinkoff.Trading.OpenApi/src/Tinkoff.Trading.OpenApi/Network/Connection.cs:line 49
   at async Task<List<Operation>> Tinkoff.Trading.OpenApi.Network.Context.OperationsAsync(DateTime from, DateTime to, string figi, string brokerAccountId) in C:/!self/github/smart-income/Libs/forks/Tinkoff.Trading.OpenApi/src/Tinkoff.Trading.OpenApi/Network/Context.cs:line 158

**Comment by qbit86** [comment]
```
IReadOnlyCollection<Account> accounts = await context.AccountsAsync().ConfigureAwait(false);
```
Такой вызов бросает исключение `Tinkoff.Trading.OpenApi.Network.OpenApiInvalidResponseException: Unable to handle response.`
Пробрасывает ошибку в методе класса `Connection<TContext>`
```
private static async Task<OpenApiResponse<TOut>> HandleResponseAsync<TOut>(HttpResponseMessage response)
```
получив такой ответ:
```
StatusCode: 403, ReasonPhrase: 'Forbidden', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers:
{
  Server: nginx
  Date: Sat, 22 Jan 2022 21:44:29 GMT
  x-edge-processing-time: 16
  Content-Length: 0
}
```

**Comment by WhiteBlackGoose** [comment]
Та же проблема.
Пример из readme:
```cs
using Tinkoff.Trading.OpenApi.Network;

var token = File.ReadAllText("mypath");

var connection = ConnectionFactory.GetConnection(token);
var context = connection.Context;

var portfolio = await context.PortfolioAsync();

foreach (var position in portfolio.Positions)
{
    Console.WriteLine(position.Figi);
}
```

Падает в `Portfolio.Async()`:
```
Unhandled exception. Tinkoff.Trading.OpenApi.Network.OpenApiInvalidResponseException: Unable to handle response.
Response:
```
<details>
<summary> <b>Продолжение stack trace</b> </summary>

```
 ---> System.Text.Json.JsonException: The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
 ---> System.Text.Json.JsonReaderException: The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](ReadOnlySpan`1 utf8Json, JsonSerializerOptions options)
   at Tinkoff.Trading.OpenApi.Network.Connection`1.HandleResponseAsync[TOut](HttpResponseMessage response)
   --- End of inner exception stack trace ---
   at Tinkoff.Trading.OpenApi.Network.Connection`1.HandleResponseAsync[TOut](HttpResponseMessage response)
   at Tinkoff.Trading.OpenApi.Network.Connection`1.SendGetRequestAsync[TPayload](String path)
   at Tinkoff.Trading.OpenApi.Network.Context.PortfolioAsync(String brokerAccountId)
   at Program.<Main>$(String[] args) in D:\main\trading\TradingAnalysis\TestCSharpDataDownload\TinkoffAPITest\Program.cs:line 9
   at Program.<Main>(String[] args)
```

</details>

**Comment by qbit86** [comment]
@WhiteBlackGoose 
У меня эта проблема перестала воспроизводиться после того, как перегенерировал токен — **полного доступа**.
Read-only токен предназначен только для нового API [2], для старого [1] не подходит.
Токен же полного доступа подходит и для нового, и для старого API.

(Это не отменяет того факта, что ошибка в коде библиотеки обрабатывается и пробрасывается неправильно.)

[1] https://github.com/Tinkoff/invest-openapi-csharp-sdk

[2] https://github.com/Tinkoff/investAPI

![read-only-token](https://user-images.githubusercontent.com/880168/152650872-292848b0-f993-4015-9a66-2a541c555724.png)

**Comment by WhiteBlackGoose** [comment]
Ух ты. Спасибо, попробую как смогу.
