### ISSUE TITLE
OperationsAsync падает на десериализации

### ISSUE THREAD

**Issue by InfernumDeus** [TinkoffCreditSystems/invest-openapi-csharp-sdk#6]
Вызов:

> await context.OperationsAsync(new DateTime(2019, 10, 10), Interval.Day, "BBG00B52KN20");

> Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.Collections.Generic.List`1[Tinkoff.Trading.OpenApi.Models.Operation]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.
> To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.
> Path 'payload.operations', line 1, position 57.
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolvePropertyAndCreatorValues(JsonObjectContract contract, JsonProperty containerProperty, JsonReader reader, Type objectType)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters(JsonReader reader, JsonObjectContract contract, JsonProperty containerProperty, ObjectConstructor`1 creator, String id)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
>    at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
>    at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
>    at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
>    at Tinkoff.Trading.OpenApi.Network.Connection`1.HandleResponseAsync[TOut](HttpResponseMessage response) in C:\Z\projects\invest-openapi-csharp-sdk\src\Tinkoff.Trading.OpenApi\Network\Connection.cs:line 78
>    at Tinkoff.Trading.OpenApi.Network.Connection`1.SendGetRequestAsync[TPayload](String path) in C:\Z\projects\invest-openapi-csharp-sdk\src\Tinkoff.Trading.OpenApi\Network\Connection.cs:line 42
>    at Tinkoff.Trading.OpenApi.Network.Context.OperationsAsync(DateTime from, Interval interval, String figi) in C:\Z\projects\invest-openapi-csharp-sdk\src\Tinkoff.Trading.OpenApi\Network\Context.cs:line 102
> 
>

**Comment by InfernumDeus** [comment]
Версия пакета 1.1.0.

**Comment by 0pd** [comment]
Fixed in #8
